type Currency = {
  name: string;
  description: string;
  code: string;
  symbol: string;
};

type Option = {
  name: string;
  flag: string;
  code: string;
  dial_code: string;
  currency: Currency;
};

export const countries: Option[] = [
  {
    name: "Afghanistan",
    flag: "🇦🇫",
    code: "AF",
    dial_code: "+93",
    currency: {
      name: "Afghani",
      description: "Afghan Afghani",
      code: "AFN",
      symbol: "؋",
    },
  },
  {
    name: "Åland Islands",
    flag: "🇦🇽",
    code: "AX",
    dial_code: "+358",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Albania",
    flag: "🇦🇱",
    code: "AL",
    dial_code: "+355",
    currency: {
      name: "Lek",
      description: "Albanian Lek",
      code: "ALL",
      symbol: "L",
    },
  },
  {
    name: "Algeria",
    flag: "🇩🇿",
    code: "DZ",
    dial_code: "+213",
    currency: {
      name: "Dinar",
      description: "Algerian Dinar",
      code: "DZD",
      symbol: "د.ج",
    },
  },
  {
    name: "American Samoa",
    flag: "🇦🇸",
    code: "AS",
    dial_code: "+1684",
    currency: {
      name: "Dollar",
      description: "US Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Andorra",
    flag: "🇦🇩",
    code: "AD",
    dial_code: "+376",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Angola",
    flag: "🇦🇴",
    code: "AO",
    dial_code: "+244",
    currency: {
      name: "Kwanza",
      description: "Angolan Kwanza",
      code: "AOA",
      symbol: "Kz",
    },
  },
  {
    name: "Anguilla",
    flag: "🇦🇮",
    code: "AI",
    dial_code: "+1264",
    currency: {
      name: "Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "$",
    },
  },
  {
    name: "Antarctica",
    flag: "🇦🇶",
    code: "AQ",
    dial_code: "+672",
    currency: {
      name: "Dollar",
      description: "No official currency",
      code: "N/A",
      symbol: "N/A",
    },
  },
  {
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    code: "AG",
    dial_code: "+1268",
    currency: {
      name: "Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "$",
    },
  },
  {
    name: "Argentina",
    flag: "🇦🇷",
    code: "AR",
    dial_code: "+54",
    currency: {
      name: "Peso",
      description: "Argentine Peso",
      code: "ARS",
      symbol: "$",
    },
  },
  {
    name: "Armenia",
    flag: "🇦🇲",
    code: "AM",
    dial_code: "+374",
    currency: {
      name: "Dram",
      description: "Armenian Dram",
      code: "AMD",
      symbol: "֏",
    },
  },
  {
    name: "Aruba",
    flag: "🇦🇼",
    code: "AW",
    dial_code: "+297",
    currency: {
      name: "Florin",
      description: "Aruban Florin",
      code: "AWG",
      symbol: "ƒ",
    },
  },
  {
    name: "Australia",
    flag: "🇦🇺",
    code: "AU",
    dial_code: "+61",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "$",
    },
  },
  {
    name: "Austria",
    flag: "🇦🇹",
    code: "AT",
    dial_code: "+43",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Azerbaijan",
    flag: "🇦🇿",
    code: "AZ",
    dial_code: "+994",
    currency: {
      name: "Manat",
      description: "Azerbaijani Manat",
      code: "AZN",
      symbol: "₼",
    },
  },
  {
    name: "Bahamas",
    flag: "🇧🇸",
    code: "BS",
    dial_code: "+1242",
    currency: {
      name: "Dollar",
      description: "Bahamian Dollar",
      code: "BSD",
      symbol: "$",
    },
  },
  {
    name: "Bahrain",
    flag: "🇧🇭",
    code: "BH",
    dial_code: "+973",
    currency: {
      name: "Dinar",
      description: "Bahraini Dinar",
      code: "BHD",
      symbol: ".د.ب",
    },
  },
  {
    name: "Bangladesh",
    flag: "🇧🇩",
    code: "BD",
    dial_code: "+880",
    currency: {
      name: "Taka",
      description: "Bangladeshi Taka",
      code: "BDT",
      symbol: "৳",
    },
  },
  {
    name: "Barbados",
    flag: "🇧🇧",
    code: "BB",
    dial_code: "+1246",
    currency: {
      name: "Dollar",
      description: "Barbadian Dollar",
      code: "BBD",
      symbol: "$",
    },
  },
  {
    name: "Belarus",
    flag: "🇧🇾",
    code: "BY",
    dial_code: "+375",
    currency: {
      name: "Ruble",
      description: "Belarusian Ruble",
      code: "BYN",
      symbol: "Br",
    },
  },
  {
    name: "Belgium",
    flag: "🇧🇪",
    code: "BE",
    dial_code: "+32",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Belize",
    flag: "🇧🇿",
    code: "BZ",
    dial_code: "+501",
    currency: {
      name: "Dollar",
      description: "Belize Dollar",
      code: "BZD",
      symbol: "$",
    },
  },
  {
    name: "Benin",
    flag: "🇧🇯",
    code: "BJ",
    dial_code: "+229",
    currency: {
      name: "Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "₣",
    },
  },
  {
    name: "Bermuda",
    flag: "🇧🇲",
    code: "BM",
    dial_code: "+1441",
    currency: {
      name: "Dollar",
      description: "Bermudian Dollar",
      code: "BMD",
      symbol: "$",
    },
  },
  {
    name: "Bhutan",
    flag: "🇧🇹",
    code: "BT",
    dial_code: "+975",
    currency: {
      name: "Ngultrum",
      description: "Bhutanese Ngultrum",
      code: "BTN",
      symbol: "Nu.",
    },
  },
  {
    name: "Bolivia, Plurinational State of bolivia",
    flag: "🇧🇴",
    code: "BO",
    dial_code: "+591",
    currency: {
      name: "Boliviano",
      description: "Bolivian Boliviano",
      code: "BOB",
      symbol: "Bs.",
    },
  },
  {
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    code: "BA",
    dial_code: "+387",
    currency: {
      name: "Mark",
      description: "Bosnia and Herzegovina Convertible Mark",
      code: "BAM",
      symbol: "КМ",
    },
  },
  {
    name: "Botswana",
    flag: "🇧🇼",
    code: "BW",
    dial_code: "+267",
    currency: {
      name: "Pula",
      description: "Botswana Pula",
      code: "BWP",
      symbol: "P",
    },
  },
  {
    name: "Bouvet Island",
    flag: "🇧🇻",
    code: "BV",
    dial_code: "+47",
    currency: {
      name: "Krone",
      description: "Norwegian Krone",
      code: "NOK",
      symbol: "kr",
    },
  },
  {
    name: "Brazil",
    flag: "🇧🇷",
    code: "BR",
    dial_code: "+55",
    currency: {
      name: "Real",
      description: "Brazilian Real",
      code: "BRL",
      symbol: "R$",
    },
  },
  {
    name: "British Indian Ocean Territory",
    flag: "🇮🇴",
    code: "IO",
    dial_code: "+246",
    currency: {
      name: "Dollar",
      description: "US Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Brunei Darussalam",
    flag: "🇧🇳",
    code: "BN",
    dial_code: "+673",
    currency: {
      name: "Dollar",
      description: "Brunei Dollar",
      code: "BND",
      symbol: "$",
    },
  },
  {
    name: "Bulgaria",
    flag: "🇧🇬",
    code: "BG",
    dial_code: "+359",
    currency: {
      name: "Lev",
      description: "Bulgarian Lev",
      code: "BGN",
      symbol: "лв",
    },
  },
  {
    name: "Burkina Faso",
    flag: "🇧🇫",
    code: "BF",
    dial_code: "+226",
    currency: {
      name: "Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "₣",
    },
  },
  {
    name: "Burundi",
    flag: "🇧🇮",
    code: "BI",
    dial_code: "+257",
    currency: {
      name: "Franc",
      description: "Burundian Franc",
      code: "BIF",
      symbol: "₣",
    },
  },
  {
    name: "Cambodia",
    flag: "🇰🇭",
    code: "KH",
    dial_code: "+855",
    currency: {
      name: "Riel",
      description: "Cambodian Riel",
      code: "KHR",
      symbol: "៛",
    },
  },
  {
    name: "Cameroon",
    flag: "🇨🇲",
    code: "CM",
    dial_code: "+237",
    currency: {
      name: "Franc",
      description: "Central African CFA Franc",
      code: "XAF",
      symbol: "₣",
    },
  },
  {
    name: "Canada",
    flag: "🇨🇦",
    code: "CA",
    dial_code: "+1",
    currency: {
      name: "Dollar",
      description: "Canadian Dollar",
      code: "CAD",
      symbol: "$",
    },
  },
  {
    name: "Cape Verde",
    flag: "🇨🇻",
    code: "CV",
    dial_code: "+238",
    currency: {
      name: "Escudo",
      description: "Cape Verdean Escudo",
      code: "CVE",
      symbol: "$",
    },
  },
  {
    name: "Cayman Islands",
    flag: "🇰🇾",
    code: "KY",
    dial_code: "+345",
    currency: {
      name: "Dollar",
      description: "Cayman Islands Dollar",
      code: "KYD",
      symbol: "$",
    },
  },
  {
    name: "Central African Republic",
    flag: "🇨🇫",
    code: "CF",
    dial_code: "+236",
    currency: {
      name: "Franc",
      description: "Central African CFA Franc",
      code: "XAF",
      symbol: "₣",
    },
  },
  {
    name: "Chad",
    flag: "🇹🇩",
    code: "TD",
    dial_code: "+235",
    currency: {
      name: "Franc",
      description: "Central African CFA Franc",
      code: "XAF",
      symbol: "₣",
    },
  },
  {
    name: "Chile",
    flag: "🇨🇱",
    code: "CL",
    dial_code: "+56",
    currency: {
      name: "Peso",
      description: "Chilean Peso",
      code: "CLP",
      symbol: "$",
    },
  },
  {
    name: "China",
    flag: "🇨🇳",
    code: "CN",
    dial_code: "+86",
    currency: {
      name: "Yuan",
      description: "Chinese Yuan",
      code: "CNY",
      symbol: "¥",
    },
  },
  {
    name: "Christmas Island",
    flag: "🇨🇽",
    code: "CX",
    dial_code: "+61",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "$",
    },
  },
  {
    name: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
    code: "CC",
    dial_code: "+61",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "$",
    },
  },
  {
    name: "Colombia",
    flag: "🇨🇴",
    code: "CO",
    dial_code: "+57",
    currency: {
      name: "Peso",
      description: "Colombian Peso",
      code: "COP",
      symbol: "$",
    },
  },
  {
    name: "Comoros",
    flag: "🇰🇲",
    code: "KM",
    dial_code: "+269",
    currency: {
      name: "Franc",
      description: "Comorian Franc",
      code: "KMF",
      symbol: "₣",
    },
  },
  {
    name: "Congo",
    flag: "🇨🇬",
    code: "CG",
    dial_code: "+242",
    currency: {
      name: "Franc",
      description: "Central African CFA Franc",
      code: "XAF",
      symbol: "₣",
    },
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    flag: "🇨🇩",
    code: "CD",
    dial_code: "+243",
    currency: {
      name: "Franc",
      description: "Congolese Franc",
      code: "CDF",
      symbol: "₣",
    },
  },
  {
    name: "Cook Islands",
    flag: "🇨🇰",
    code: "CK",
    dial_code: "+682",
    currency: {
      name: "Dollar",
      description: "New Zealand Dollar",
      code: "NZD",
      symbol: "$",
    },
  },
  {
    name: "Costa Rica",
    flag: "🇨🇷",
    code: "CR",
    dial_code: "+506",
    currency: {
      name: "Colón",
      description: "Costa Rican Colón",
      code: "CRC",
      symbol: "₡",
    },
  },
  {
    name: "Cote d'Ivoire",
    flag: "🇨🇮",
    code: "CI",
    dial_code: "+225",
    currency: {
      name: "Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "₣",
    },
  },
  {
    name: "Croatia",
    flag: "🇭🇷",
    code: "HR",
    dial_code: "+385",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Cuba",
    flag: "🇨🇺",
    code: "CU",
    dial_code: "+53",
    currency: {
      name: "Peso",
      description: "Cuban Peso",
      code: "CUP",
      symbol: "$",
    },
  },
  {
    name: "Cyprus",
    flag: "🇨🇾",
    code: "CY",
    dial_code: "+357",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Czech Republic",
    flag: "🇨🇿",
    code: "CZ",
    dial_code: "+420",
    currency: {
      name: "Koruna",
      description: "Czech Koruna",
      code: "CZK",
      symbol: "Kč",
    },
  },
  {
    name: "Denmark",
    flag: "🇩🇰",
    code: "DK",
    dial_code: "+45",
    currency: {
      name: "Krone",
      description: "Danish Krone",
      code: "DKK",
      symbol: "kr",
    },
  },
  {
    name: "Djibouti",
    flag: "🇩🇯",
    code: "DJ",
    dial_code: "+253",
    currency: {
      name: "Franc",
      description: "Djiboutian Franc",
      code: "DJF",
      symbol: "₣",
    },
  },
  {
    name: "Dominica",
    flag: "🇩🇲",
    code: "DM",
    dial_code: "+1767",
    currency: {
      name: "Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "$",
    },
  },
  {
    name: "Dominican Republic",
    flag: "🇩🇴",
    code: "DO",
    dial_code: "+1849",
    currency: {
      name: "Peso",
      description: "Dominican Peso",
      code: "DOP",
      symbol: "$",
    },
  },
  {
    name: "Ecuador",
    flag: "🇪🇨",
    code: "EC",
    dial_code: "+593",
    currency: {
      name: "Dollar",
      description: "US Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Egypt",
    flag: "🇪🇬",
    code: "EG",
    dial_code: "+20",
    currency: {
      name: "Pound",
      description: "Egyptian Pound",
      code: "EGP",
      symbol: "£",
    },
  },
  {
    name: "El Salvador",
    flag: "🇸🇻",
    code: "SV",
    dial_code: "+503",
    currency: {
      name: "Dollar",
      description: "US Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    code: "GQ",
    dial_code: "+240",
    currency: {
      name: "Franc",
      description: "Central African CFA Franc",
      code: "XAF",
      symbol: "₣",
    },
  },
  {
    name: "Eritrea",
    flag: "🇪🇷",
    code: "ER",
    dial_code: "+291",
    currency: {
      name: "Nakfa",
      description: "Eritrean Nakfa",
      code: "ERN",
      symbol: "Nfk",
    },
  },
  {
    name: "Estonia",
    flag: "🇪🇪",
    code: "EE",
    dial_code: "+372",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Ethiopia",
    flag: "🇪🇹",
    code: "ET",
    dial_code: "+251",
    currency: {
      name: "Birr",
      description: "Ethiopian Birr",
      code: "ETB",
      symbol: "Br",
    },
  },
  {
    name: "Falkland Islands (Malvinas)",
    flag: "🇫🇰",
    code: "FK",
    dial_code: "+500",
    currency: {
      name: "Pound",
      description: "Falkland Islands Pound",
      code: "FKP",
      symbol: "£",
    },
  },
  {
    name: "Faroe Islands",
    flag: "🇫🇴",
    code: "FO",
    dial_code: "+298",
    currency: {
      name: "Krone",
      description: "Faroese Króna",
      code: "DKK",
      symbol: "kr",
    },
  },
  {
    name: "Fiji",
    flag: "🇫🇯",
    code: "FJ",
    dial_code: "+679",
    currency: {
      name: "Dollar",
      description: "Fijian Dollar",
      code: "FJD",
      symbol: "$",
    },
  },
  {
    name: "Finland",
    flag: "🇫🇮",
    code: "FI",
    dial_code: "+358",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "France",
    flag: "🇫🇷",
    code: "FR",
    dial_code: "+33",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "French Guiana",
    flag: "🇬🇫",
    code: "GF",
    dial_code: "+594",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "French Polynesia",
    flag: "🇵🇫",
    code: "PF",
    dial_code: "+689",
    currency: {
      name: "Franc",
      description: "CFP Franc",
      code: "XPF",
      symbol: "₣",
    },
  },
  {
    name: "French Southern Territories",
    flag: "🇹🇫",
    code: "TF",
    dial_code: "+262",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Gabon",
    flag: "🇬🇦",
    code: "GA",
    dial_code: "+241",
    currency: {
      name: "Franc",
      description: "Central African CFA Franc",
      code: "XAF",
      symbol: "₣",
    },
  },
  {
    name: "Gambia",
    flag: "🇬🇲",
    code: "GM",
    dial_code: "+220",
    currency: {
      name: "Dalasi",
      description: "Gambian Dalasi",
      code: "GMD",
      symbol: "D",
    },
  },
  {
    name: "Georgia",
    flag: "🇬🇪",
    code: "GE",
    dial_code: "+995",
    currency: {
      name: "Lari",
      description: "Georgian Lari",
      code: "GEL",
      symbol: "₾",
    },
  },
  {
    name: "Germany",
    flag: "🇩🇪",
    code: "DE",
    dial_code: "+49",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Ghana",
    flag: "🇬🇭",
    code: "GH",
    dial_code: "+233",
    currency: {
      name: "Cedi",
      description: "Ghanaian Cedi",
      code: "GHS",
      symbol: "₵",
    },
  },
  {
    name: "Gibraltar",
    flag: "🇬🇮",
    code: "GI",
    dial_code: "+350",
    currency: {
      name: "Pound",
      description: "Gibraltar Pound",
      code: "GIP",
      symbol: "£",
    },
  },
  {
    name: "Greece",
    flag: "🇬🇷",
    code: "GR",
    dial_code: "+30",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Greenland",
    flag: "🇬🇱",
    code: "GL",
    dial_code: "+299",
    currency: {
      name: "Krone",
      description: "Danish Krone",
      code: "DKK",
      symbol: "kr",
    },
  },
  {
    name: "Grenada",
    flag: "🇬🇩",
    code: "GD",
    dial_code: "+1473",
    currency: {
      name: "Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "$",
    },
  },
  {
    name: "Guadeloupe",
    flag: "🇬🇵",
    code: "GP",
    dial_code: "+590",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Guam",
    flag: "🇬🇺",
    code: "GU",
    dial_code: "+1671",
    currency: {
      name: "Dollar",
      description: "US Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Guatemala",
    flag: "🇬🇹",
    code: "GT",
    dial_code: "+502",
    currency: {
      name: "Quetzal",
      description: "Guatemalan Quetzal",
      code: "GTQ",
      symbol: "Q",
    },
  },
  {
    name: "Guernsey",
    flag: "🇬🇬",
    code: "GG",
    dial_code: "+44",
    currency: {
      name: "Pound",
      description: "Guernsey Pound",
      code: "GGP",
      symbol: "£",
    },
  },
  {
    name: "Guinea",
    flag: "🇬🇳",
    code: "GN",
    dial_code: "+224",
    currency: {
      name: "Franc",
      description: "Guinean Franc",
      code: "GNF",
      symbol: "₣",
    },
  },
  {
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    code: "GW",
    dial_code: "+245",
    currency: {
      name: "Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "₣",
    },
  },
  {
    name: "Guyana",
    flag: "🇬🇾",
    code: "GY",
    dial_code: "+592",
    currency: {
      name: "Dollar",
      description: "Guyanese Dollar",
      code: "GYD",
      symbol: "$",
    },
  },
  {
    name: "Haiti",
    flag: "🇭🇹",
    code: "HT",
    dial_code: "+509",
    currency: {
      name: "Gourde",
      description: "Haitian Gourde",
      code: "HTG",
      symbol: "G",
    },
  },
  {
    name: "Heard Island and Mcdonald Islands",
    flag: "🇭🇲",
    code: "HM",
    dial_code: "+672",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "$",
    },
  },
  {
    name: "Holy See (Vatican City State)",
    flag: "🇻🇦",
    code: "VA",
    dial_code: "+379",
    currency: { name: "Euro", description: "Euro", code: "EUR", symbol: "€" },
  },
  {
    name: "Honduras",
    flag: "🇭🇳",
    code: "HN",
    dial_code: "+504",
    currency: {
      name: "Lempira",
      description: "Honduran Lempira",
      code: "HNL",
      symbol: "L",
    },
  },
  {
    name: "Hong Kong",
    flag: "🇭🇰",
    code: "HK",
    dial_code: "+852",
    currency: {
      name: "Dollar",
      description: "Hong Kong Dollar",
      code: "HKD",
      symbol: "$",
    },
  },
  {
    name: "Hungary",
    flag: "🇭🇺",
    code: "HU",
    dial_code: "+36",
    currency: {
      name: "Forint",
      description: "Hungarian Forint",
      code: "HUF",
      symbol: "Ft",
    },
  },
  {
    name: "Iceland",
    flag: "🇮🇸",
    code: "IS",
    dial_code: "+354",
    currency: {
      name: "Króna",
      description: "Icelandic Króna",
      code: "ISK",
      symbol: "kr",
    },
  },
  {
    name: "India",
    flag: "🇮🇳",
    code: "IN",
    dial_code: "+91",
    currency: {
      name: "Rupee",
      description: "Indian Rupee",
      code: "INR",
      symbol: "₹",
    },
  },

  {
    name: "Indonesia",
    flag: "🇮🇩",
    code: "ID",
    dial_code: "+62",
    currency: {
      name: "Rupiah",
      description: "Indonesian Rupiah",
      code: "IDR",
      symbol: "Rp",
    },
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    flag: "🇮🇷",
    code: "IR",
    dial_code: "+98",
    currency: {
      name: "Rial",
      description: "Iranian Rial",
      code: "IRR",
      symbol: "﷼",
    },
  },
  {
    name: "Iraq",
    flag: "🇮🇶",
    code: "IQ",
    dial_code: "+964",
    currency: {
      name: "Dinar",
      description: "Iraqi Dinar",
      code: "IQD",
      symbol: "ع.د",
    },
  },
  {
    name: "Ireland",
    flag: "🇮🇪",
    code: "IE",
    dial_code: "+353",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Isle of Man",
    flag: "🇮🇲",
    code: "IM",
    dial_code: "+44",
    currency: {
      name: "Pound",
      description: "British Pound Sterling",
      code: "GBP",
      symbol: "£",
    },
  },
  {
    name: "Israel",
    flag: "🇮🇱",
    code: "IL",
    dial_code: "+972",
    currency: {
      name: "Shekel",
      description: "Israeli New Shekel",
      code: "ILS",
      symbol: "₪",
    },
  },
  {
    name: "Italy",
    flag: "🇮🇹",
    code: "IT",
    dial_code: "+39",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Jamaica",
    flag: "🇯🇲",
    code: "JM",
    dial_code: "+1876",
    currency: {
      name: "Dollar",
      description: "Jamaican Dollar",
      code: "JMD",
      symbol: "J$",
    },
  },
  {
    name: "Japan",
    flag: "🇯🇵",
    code: "JP",
    dial_code: "+81",
    currency: {
      name: "Yen",
      description: "Japanese Yen",
      code: "JPY",
      symbol: "¥",
    },
  },
  {
    name: "Jersey",
    flag: "🇯🇪",
    code: "JE",
    dial_code: "+44",
    currency: {
      name: "Pound",
      description: "British Pound Sterling",
      code: "GBP",
      symbol: "£",
    },
  },
  {
    name: "Jordan",
    flag: "🇯🇴",
    code: "JO",
    dial_code: "+962",
    currency: {
      name: "Dinar",
      description: "Jordanian Dinar",
      code: "JOD",
      symbol: "د.ا",
    },
  },
  {
    name: "Kazakhstan",
    flag: "🇰🇿",
    code: "KZ",
    dial_code: "+7",
    currency: {
      name: "Tenge",
      description: "Kazakhstani Tenge",
      code: "KZT",
      symbol: "₸",
    },
  },
  {
    name: "Kenya",
    flag: "🇰🇪",
    code: "KE",
    dial_code: "+254",
    currency: {
      name: "Shilling",
      description: "Kenyan Shilling",
      code: "KES",
      symbol: "KSh",
    },
  },
  {
    name: "Kiribati",
    flag: "🇰🇮",
    code: "KI",
    dial_code: "+686",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "A$",
    },
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    flag: "🇰🇵",
    code: "KP",
    dial_code: "+850",
    currency: {
      name: "Won",
      description: "North Korean Won",
      code: "KPW",
      symbol: "₩",
    },
  },
  {
    name: "Korea, Republic of South Korea",
    flag: "🇰🇷",
    code: "KR",
    dial_code: "+82",
    currency: {
      name: "Won",
      description: "South Korean Won",
      code: "KRW",
      symbol: "₩",
    },
  },
  {
    name: "Kosovo",
    flag: "🇽🇰",
    code: "XK",
    dial_code: "+383",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Kuwait",
    flag: "🇰🇼",
    code: "KW",
    dial_code: "+965",
    currency: {
      name: "Dinar",
      description: "Kuwaiti Dinar",
      code: "KWD",
      symbol: "د.ك",
    },
  },
  {
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    code: "KG",
    dial_code: "+996",
    currency: {
      name: "Som",
      description: "Kyrgyzstani Som",
      code: "KGS",
      symbol: "лв",
    },
  },
  {
    name: "Laos",
    flag: "🇱🇦",
    code: "LA",
    dial_code: "+856",
    currency: {
      name: "Kip",
      description: "Lao Kip",
      code: "LAK",
      symbol: "₭",
    },
  },
  {
    name: "Latvia",
    flag: "🇱🇻",
    code: "LV",
    dial_code: "+371",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Lebanon",
    flag: "🇱🇧",
    code: "LB",
    dial_code: "+961",
    currency: {
      name: "Pound",
      description: "Lebanese Pound",
      code: "LBP",
      symbol: "ل.ل",
    },
  },
  {
    name: "Lesotho",
    flag: "🇱🇸",
    code: "LS",
    dial_code: "+266",
    currency: {
      name: "Loti",
      description: "Lesotho Loti",
      code: "LSL",
      symbol: "L",
    },
  },
  {
    name: "Liberia",
    flag: "🇱🇷",
    code: "LR",
    dial_code: "+231",
    currency: {
      name: "Dollar",
      description: "Liberian Dollar",
      code: "LRD",
      symbol: "L$",
    },
  },
  {
    name: "Libyan Arab Jamahiriya",
    flag: "🇱🇾",
    code: "LY",
    dial_code: "+218",
    currency: {
      name: "Dinar",
      description: "Libyan Dinar",
      code: "LYD",
      symbol: "ل.د",
    },
  },
  {
    name: "Liechtenstein",
    flag: "🇱🇮",
    code: "LI",
    dial_code: "+423",
    currency: {
      name: "Franc",
      description: "Swiss Franc",
      code: "CHF",
      symbol: "Fr",
    },
  },
  {
    name: "Lithuania",
    flag: "🇱🇹",
    code: "LT",
    dial_code: "+370",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Luxembourg",
    flag: "🇱🇺",
    code: "LU",
    dial_code: "+352",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Macao",
    flag: "🇲🇴",
    code: "MO",
    dial_code: "+853",
    currency: {
      name: "Pataca",
      description: "Macanese Pataca",
      code: "MOP",
      symbol: "MOP$",
    },
  },
  {
    name: "Macedonia",
    flag: "🇲🇰",
    code: "MK",
    dial_code: "+389",
    currency: {
      name: "Denar",
      description: "Macedonian Denar",
      code: "MKD",
      symbol: "ден",
    },
  },
  {
    name: "Madagascar",
    flag: "🇲🇬",
    code: "MG",
    dial_code: "+261",
    currency: {
      name: "Ariary",
      description: "Malagasy Ariary",
      code: "MGA",
      symbol: "Ar",
    },
  },
  {
    name: "Malawi",
    flag: "🇲🇼",
    code: "MW",
    dial_code: "+265",
    currency: {
      name: "Kwacha",
      description: "Malawian Kwacha",
      code: "MWK",
      symbol: "MK",
    },
  },
  {
    name: "Malaysia",
    flag: "🇲🇾",
    code: "MY",
    dial_code: "+60",
    currency: {
      name: "Ringgit",
      description: "Malaysian Ringgit",
      code: "MYR",
      symbol: "RM",
    },
  },
  {
    name: "Maldives",
    flag: "🇲🇻",
    code: "MV",
    dial_code: "+960",
    currency: {
      name: "Rufiyaa",
      description: "Maldivian Rufiyaa",
      code: "MVR",
      symbol: "Rf",
    },
  },
  {
    name: "Mali",
    flag: "🇲🇱",
    code: "ML",
    dial_code: "+223",
    currency: {
      name: "Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "Fr",
    },
  },
  {
    name: "Malta",
    flag: "🇲🇹",
    code: "MT",
    dial_code: "+356",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Marshall Islands",
    flag: "🇲🇭",
    code: "MH",
    dial_code: "+692",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Martinique",
    flag: "🇲🇶",
    code: "MQ",
    dial_code: "+596",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Mauritania",
    flag: "🇲🇷",
    code: "MR",
    dial_code: "+222",
    currency: {
      name: "Ouguiya",
      description: "Mauritanian Ouguiya",
      code: "MRU",
      symbol: "UM",
    },
  },
  {
    name: "Mauritius",
    flag: "🇲🇺",
    code: "MU",
    dial_code: "+230",
    currency: {
      name: "Rupee",
      description: "Mauritian Rupee",
      code: "MUR",
      symbol: "₨",
    },
  },
  {
    name: "Mayotte",
    flag: "🇾🇹",
    code: "YT",
    dial_code: "+262",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Mexico",
    flag: "🇲🇽",
    code: "MX",
    dial_code: "+52",
    currency: {
      name: "Peso",
      description: "Mexican Peso",
      code: "MXN",
      symbol: "$",
    },
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    flag: "🇫🇲",
    code: "FM",
    dial_code: "+691",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Moldova",
    flag: "🇲🇩",
    code: "MD",
    dial_code: "+373",
    currency: {
      name: "Leu",
      description: "Moldovan Leu",
      code: "MDL",
      symbol: "L",
    },
  },
  {
    name: "Monaco",
    flag: "🇲🇨",
    code: "MC",
    dial_code: "+377",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Mongolia",
    flag: "🇲🇳",
    code: "MN",
    dial_code: "+976",
    currency: {
      name: "Tugrik",
      description: "Mongolian Tugrik",
      code: "MNT",
      symbol: "₮",
    },
  },
  {
    name: "Montenegro",
    flag: "🇲🇪",
    code: "ME",
    dial_code: "+382",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Montserrat",
    flag: "🇲🇸",
    code: "MS",
    dial_code: "+1664",
    currency: {
      name: "Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "EC$",
    },
  },
  {
    name: "Morocco",
    flag: "🇲🇦",
    code: "MA",
    dial_code: "+212",
    currency: {
      name: "Dirham",
      description: "Moroccan Dirham",
      code: "MAD",
      symbol: "د.م.",
    },
  },
  {
    name: "Mozambique",
    flag: "🇲🇿",
    code: "MZ",
    dial_code: "+258",
    currency: {
      name: "Metical",
      description: "Mozambican Metical",
      code: "MZN",
      symbol: "MT",
    },
  },
  {
    name: "Myanmar",
    flag: "🇲🇲",
    code: "MM",
    dial_code: "+95",
    currency: {
      name: "Kyat",
      description: "Myanmar Kyat",
      code: "MMK",
      symbol: "K",
    },
  },
  {
    name: "Namibia",
    flag: "🇳🇦",
    code: "NA",
    dial_code: "+264",
    currency: {
      name: "Dollar",
      description: "Namibian Dollar",
      code: "NAD",
      symbol: "N$",
    },
  },
  {
    name: "Nauru",
    flag: "🇳🇷",
    code: "NR",
    dial_code: "+674",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "A$",
    },
  },
  {
    name: "Nepal",
    flag: "🇳🇵",
    code: "NP",
    dial_code: "+977",
    currency: {
      name: "Rupee",
      description: "Nepalese Rupee",
      code: "NPR",
      symbol: "₨",
    },
  },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    code: "NL",
    dial_code: "+31",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Netherlands Antilles",
    flag: "",
    code: "AN",
    dial_code: "+599",
    currency: {
      name: "Guilder",
      description: "Netherlands Antillean Guilder",
      code: "ANG",
      symbol: "ƒ",
    },
  },
  {
    name: "New Caledonia",
    flag: "🇳🇨",
    code: "NC",
    dial_code: "+687",
    currency: {
      name: "Franc",
      description: "CFP Franc",
      code: "XPF",
      symbol: "Fr",
    },
  },
  {
    name: "New Zealand",
    flag: "🇳🇿",
    code: "NZ",
    dial_code: "+64",
    currency: {
      name: "Dollar",
      description: "New Zealand Dollar",
      code: "NZD",
      symbol: "NZ$",
    },
  },
  {
    name: "Nicaragua",
    flag: "🇳🇮",
    code: "NI",
    dial_code: "+505",
    currency: {
      name: "Córdoba",
      description: "Nicaraguan Córdoba",
      code: "NIO",
      symbol: "C$",
    },
  },
  {
    name: "Niger",
    flag: "🇳🇪",
    code: "NE",
    dial_code: "+227",
    currency: {
      name: "Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "Fr",
    },
  },
  {
    name: "Nigeria",
    flag: "🇳🇬",
    code: "NG",
    dial_code: "+234",
    currency: {
      name: "Naira",
      description: "Nigerian Naira",
      code: "NGN",
      symbol: "₦",
    },
  },
  {
    name: "Niue",
    flag: "🇳🇺",
    code: "NU",
    dial_code: "+683",
    currency: {
      name: "Dollar",
      description: "New Zealand Dollar",
      code: "NZD",
      symbol: "NZ$",
    },
  },
  {
    name: "Norfolk Island",
    flag: "🇳🇫",
    code: "NF",
    dial_code: "+672",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "A$",
    },
  },
  {
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
    code: "MP",
    dial_code: "+1670",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Norway",
    flag: "🇳🇴",
    code: "NO",
    dial_code: "+47",
    currency: {
      name: "Krone",
      description: "Norwegian Krone",
      code: "NOK",
      symbol: "kr",
    },
  },
  {
    name: "Oman",
    flag: "🇴🇲",
    code: "OM",
    dial_code: "+968",
    currency: {
      name: "Rial",
      description: "Omani Rial",
      code: "OMR",
      symbol: "ر.ع.",
    },
  },
  {
    name: "Pakistan",
    flag: "🇵🇰",
    code: "PK",
    dial_code: "+92",
    currency: {
      name: "Rupee",
      description: "Pakistani Rupee",
      code: "PKR",
      symbol: "₨",
    },
  },
  {
    name: "Palau",
    flag: "🇵🇼",
    code: "PW",
    dial_code: "+680",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Palestinian Territory, Occupied",
    flag: "🇵🇸",
    code: "PS",
    dial_code: "+970",
    currency: {
      name: "Shekel",
      description: "Israeli New Shekel",
      code: "ILS",
      symbol: "₪",
    },
  },
  {
    name: "Panama",
    flag: "🇵🇦",
    code: "PA",
    dial_code: "+507",
    currency: {
      name: "Balboa",
      description: "Panamanian Balboa",
      code: "PAB",
      symbol: "B/.",
    },
  },
  {
    name: "Papua New Guinea",
    flag: "🇵🇬",
    code: "PG",
    dial_code: "+675",
    currency: {
      name: "Kina",
      description: "Papua New Guinean Kina",
      code: "PGK",
      symbol: "K",
    },
  },
  {
    name: "Paraguay",
    flag: "🇵🇾",
    code: "PY",
    dial_code: "+595",
    currency: {
      name: "Guarani",
      description: "Paraguayan Guarani",
      code: "PYG",
      symbol: "₲",
    },
  },
  {
    name: "Peru",
    flag: "🇵🇪",
    code: "PE",
    dial_code: "+51",
    currency: {
      name: "Sol",
      description: "Peruvian Sol",
      code: "PEN",
      symbol: "S/",
    },
  },
  {
    name: "Philippines",
    flag: "🇵🇭",
    code: "PH",
    dial_code: "+63",
    currency: {
      name: "Peso",
      description: "Philippine Peso",
      code: "PHP",
      symbol: "₱",
    },
  },
  {
    name: "Pitcairn",
    flag: "🇵🇳",
    code: "PN",
    dial_code: "+64",
    currency: {
      name: "Dollar",
      description: "New Zealand Dollar",
      code: "NZD",
      symbol: "NZ$",
    },
  },
  {
    name: "Poland",
    flag: "🇵🇱",
    code: "PL",
    dial_code: "+48",
    currency: {
      name: "Zloty",
      description: "Polish Zloty",
      code: "PLN",
      symbol: "zł",
    },
  },
  {
    name: "Portugal",
    flag: "🇵🇹",
    code: "PT",
    dial_code: "+351",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Puerto Rico",
    flag: "🇵🇷",
    code: "PR",
    dial_code: "+1939",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Qatar",
    flag: "🇶🇦",
    code: "QA",
    dial_code: "+974",
    currency: {
      name: "Riyal",
      description: "Qatari Riyal",
      code: "QAR",
      symbol: "ر.ق",
    },
  },
  {
    name: "Romania",
    flag: "🇷🇴",
    code: "RO",
    dial_code: "+40",
    currency: {
      name: "Leu",
      description: "Romanian Leu",
      code: "RON",
      symbol: "lei",
    },
  },
  {
    name: "Russia",
    flag: "🇷🇺",
    code: "RU",
    dial_code: "+7",
    currency: {
      name: "Ruble",
      description: "Russian Ruble",
      code: "RUB",
      symbol: "₽",
    },
  },
  {
    name: "Rwanda",
    flag: "🇷🇼",
    code: "RW",
    dial_code: "+250",
    currency: {
      name: "Franc",
      description: "Rwandan Franc",
      code: "RWF",
      symbol: "Fr",
    },
  },
  {
    name: "Reunion",
    flag: "🇷🇪",
    code: "RE",
    dial_code: "+262",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Saint Barthelemy",
    flag: "🇧🇱",
    code: "BL",
    dial_code: "+590",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "🇸🇭",
    code: "SH",
    dial_code: "+290",
    currency: {
      name: "Pound",
      description: "Saint Helena Pound",
      code: "SHP",
      symbol: "£",
    },
  },
  {
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    code: "KN",
    dial_code: "+1869",
    currency: {
      name: "Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "EC$",
    },
  },
  {
    name: "Saint Lucia",
    flag: "🇱🇨",
    code: "LC",
    dial_code: "+1758",
    currency: {
      name: "Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "EC$",
    },
  },
  {
    name: "Saint Martin",
    flag: "🇲🇫",
    code: "MF",
    dial_code: "+590",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    code: "PM",
    dial_code: "+508",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    code: "VC",
    dial_code: "+1784",
    currency: {
      name: "East Caribbean Dollar",
      description: "East Caribbean Dollar",
      code: "XCD",
      symbol: "$",
    },
  },
  {
    name: "Samoa",
    flag: "🇼🇸",
    code: "WS",
    dial_code: "+685",
    currency: {
      name: "Tala",
      description: "Samoan Tala",
      code: "WST",
      symbol: "$",
    },
  },
  {
    name: "San Marino",
    flag: "🇸🇲",
    code: "SM",
    dial_code: "+378",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    code: "ST",
    dial_code: "+239",
    currency: {
      name: "Dobra",
      description: "São Tomé and Príncipe Dobra",
      code: "STN",
      symbol: "Db",
    },
  },
  {
    name: "Saudi Arabia",
    flag: "🇸🇦",
    code: "SA",
    dial_code: "+966",
    currency: {
      name: "Riyal",
      description: "Saudi Riyal",
      code: "SAR",
      symbol: "﷼",
    },
  },
  {
    name: "Senegal",
    flag: "🇸🇳",
    code: "SN",
    dial_code: "+221",
    currency: {
      name: "CFA Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "CFA",
    },
  },
  {
    name: "Serbia",
    flag: "🇷🇸",
    code: "RS",
    dial_code: "+381",
    currency: {
      name: "Dinar",
      description: "Serbian Dinar",
      code: "RSD",
      symbol: "дин",
    },
  },
  {
    name: "Seychelles",
    flag: "🇸🇨",
    code: "SC",
    dial_code: "+248",
    currency: {
      name: "Rupee",
      description: "Seychellois Rupee",
      code: "SCR",
      symbol: "₨",
    },
  },
  {
    name: "Sierra Leone",
    flag: "🇸🇱",
    code: "SL",
    dial_code: "+232",
    currency: {
      name: "Leone",
      description: "Sierra Leonean Leone",
      code: "SLL",
      symbol: "Le",
    },
  },
  {
    name: "Singapore",
    flag: "🇸🇬",
    code: "SG",
    dial_code: "+65",
    currency: {
      name: "Dollar",
      description: "Singapore Dollar",
      code: "SGD",
      symbol: "$",
    },
  },
  {
    name: "Slovakia",
    flag: "🇸🇰",
    code: "SK",
    dial_code: "+421",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Slovenia",
    flag: "🇸🇮",
    code: "SI",
    dial_code: "+386",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Solomon Islands",
    flag: "🇸🇧",
    code: "SB",
    dial_code: "+677",
    currency: {
      name: "Dollar",
      description: "Solomon Islands Dollar",
      code: "SBD",
      symbol: "$",
    },
  },
  {
    name: "Somalia",
    flag: "🇸🇴",
    code: "SO",
    dial_code: "+252",
    currency: {
      name: "Shilling",
      description: "Somali Shilling",
      code: "SOS",
      symbol: "S",
    },
  },
  {
    name: "South Africa",
    flag: "🇿🇦",
    code: "ZA",
    dial_code: "+27",
    currency: {
      name: "Rand",
      description: "South African Rand",
      code: "ZAR",
      symbol: "R",
    },
  },
  {
    name: "South Sudan",
    flag: "🇸🇸",
    code: "SS",
    dial_code: "+211",
    currency: {
      name: "Pound",
      description: "South Sudanese Pound",
      code: "SSP",
      symbol: "£",
    },
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    code: "GS",
    dial_code: "+500",
    currency: {
      name: "Pound",
      description: "Falkland Islands Pound",
      code: "FKP",
      symbol: "£",
    },
  },
  {
    name: "Spain",
    flag: "🇪🇸",
    code: "ES",
    dial_code: "+34",
    currency: {
      name: "Euro",
      description: "Euro",
      code: "EUR",
      symbol: "€",
    },
  },
  {
    name: "Sri Lanka",
    flag: "🇱🇰",
    code: "LK",
    dial_code: "+94",
    currency: {
      name: "Rupee",
      description: "Sri Lankan Rupee",
      code: "LKR",
      symbol: "₨",
    },
  },
  {
    name: "Sudan",
    flag: "🇸🇩",
    code: "SD",
    dial_code: "+249",
    currency: {
      name: "Pound",
      description: "Sudanese Pound",
      code: "SDG",
      symbol: "ج.س",
    },
  },
  {
    name: "Suriname",
    flag: "🇸🇷",
    code: "SR",
    dial_code: "+597",
    currency: {
      name: "Dollar",
      description: "Surinamese Dollar",
      code: "SRD",
      symbol: "$",
    },
  },
  {
    name: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    code: "SJ",
    dial_code: "+47",
    currency: {
      name: "Krone",
      description: "Norwegian Krone",
      code: "NOK",
      symbol: "kr",
    },
  },
  {
    name: "Swaziland",
    flag: "🇸🇿",
    code: "SZ",
    dial_code: "+268",
    currency: {
      name: "Lilangeni",
      description: "Swazi Lilangeni",
      code: "SZL",
      symbol: "L",
    },
  },
  {
    name: "Sweden",
    flag: "🇸🇪",
    code: "SE",
    dial_code: "+46",
    currency: {
      name: "Krona",
      description: "Swedish Krona",
      code: "SEK",
      symbol: "kr",
    },
  },
  {
    name: "Switzerland",
    flag: "🇨🇭",
    code: "CH",
    dial_code: "+41",
    currency: {
      name: "Franc",
      description: "Swiss Franc",
      code: "CHF",
      symbol: "CHF",
    },
  },
  {
    name: "Syrian Arab Republic",
    flag: "🇸🇾",
    code: "SY",
    dial_code: "+963",
    currency: {
      name: "Pound",
      description: "Syrian Pound",
      code: "SYP",
      symbol: "£",
    },
  },
  {
    name: "Taiwan",
    flag: "🇹🇼",
    code: "TW",
    dial_code: "+886",
    currency: {
      name: "Dollar",
      description: "New Taiwan Dollar",
      code: "TWD",
      symbol: "NT$",
    },
  },
  {
    name: "Tajikistan",
    flag: "🇹🇯",
    code: "TJ",
    dial_code: "+992",
    currency: {
      name: "Somoni",
      description: "Tajikistani Somoni",
      code: "TJS",
      symbol: "SM",
    },
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    flag: "🇹🇿",
    code: "TZ",
    dial_code: "+255",
    currency: {
      name: "Shilling",
      description: "Tanzanian Shilling",
      code: "TZS",
      symbol: "TSh",
    },
  },
  {
    name: "Thailand",
    flag: "🇹🇭",
    code: "TH",
    dial_code: "+66",
    currency: {
      name: "Baht",
      description: "Thai Baht",
      code: "THB",
      symbol: "฿",
    },
  },
  {
    name: "Timor-Leste",
    flag: "🇹🇱",
    code: "TL",
    dial_code: "+670",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Togo",
    flag: "🇹🇬",
    code: "TG",
    dial_code: "+228",
    currency: {
      name: "CFA Franc",
      description: "West African CFA Franc",
      code: "XOF",
      symbol: "CFA",
    },
  },
  {
    name: "Tokelau",
    flag: "🇹🇰",
    code: "TK",
    dial_code: "+690",
    currency: {
      name: "Dollar",
      description: "New Zealand Dollar",
      code: "NZD",
      symbol: "$",
    },
  },
  {
    name: "Tonga",
    flag: "🇹🇴",
    code: "TO",
    dial_code: "+676",
    currency: {
      name: "Paʻanga",
      description: "Tongan Paʻanga",
      code: "TOP",
      symbol: "T$",
    },
  },
  {
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    code: "TT",
    dial_code: "+1868",
    currency: {
      name: "Dollar",
      description: "Trinidad and Tobago Dollar",
      code: "TTD",
      symbol: "TT$",
    },
  },
  {
    name: "Tunisia",
    flag: "🇹🇳",
    code: "TN",
    dial_code: "+216",
    currency: {
      name: "Dinar",
      description: "Tunisian Dinar",
      code: "TND",
      symbol: "د.ت",
    },
  },
  {
    name: "Turkey",
    flag: "🇹🇷",
    code: "TR",
    dial_code: "+90",
    currency: {
      name: "Lira",
      description: "Turkish Lira",
      code: "TRY",
      symbol: "₺",
    },
  },
  {
    name: "Turkmenistan",
    flag: "🇹🇲",
    code: "TM",
    dial_code: "+993",
    currency: {
      name: "Manat",
      description: "Turkmenistani Manat",
      code: "TMT",
      symbol: "T",
    },
  },
  {
    name: "Turks and Caicos Islands",
    flag: "🇹🇨",
    code: "TC",
    dial_code: "+1649",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Tuvalu",
    flag: "🇹🇻",
    code: "TV",
    dial_code: "+688",
    currency: {
      name: "Dollar",
      description: "Australian Dollar",
      code: "AUD",
      symbol: "$",
    },
  },
  {
    name: "Uganda",
    flag: "🇺🇬",
    code: "UG",
    dial_code: "+256",
    currency: {
      name: "Shilling",
      description: "Ugandan Shilling",
      code: "UGX",
      symbol: "USh",
    },
  },
  {
    name: "Ukraine",
    flag: "🇺🇦",
    code: "UA",
    dial_code: "+380",
    currency: {
      name: "Hryvnia",
      description: "Ukrainian Hryvnia",
      code: "UAH",
      symbol: "₴",
    },
  },
  {
    name: "United Arab Emirates",
    flag: "🇦🇪",
    code: "AE",
    dial_code: "+971",
    currency: {
      name: "Dirham",
      description: "UAE Dirham",
      code: "AED",
      symbol: "د.إ",
    },
  },
  {
    name: "United Kingdom",
    flag: "🇬🇧",
    code: "GB",
    dial_code: "+44",
    currency: {
      name: "Pound",
      description: "British Pound Sterling",
      code: "GBP",
      symbol: "£",
    },
  },
  {
    name: "United States",
    flag: "🇺🇸",
    code: "US",
    dial_code: "+1",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Uruguay",
    flag: "🇺🇾",
    code: "UY",
    dial_code: "+598",
    currency: {
      name: "Peso",
      description: "Uruguayan Peso",
      code: "UYU",
      symbol: "$U",
    },
  },
  {
    name: "Uzbekistan",
    flag: "🇺🇿",
    code: "UZ",
    dial_code: "+998",
    currency: {
      name: "Som",
      description: "Uzbekistan Som",
      code: "UZS",
      symbol: "лв",
    },
  },
  {
    name: "Vanuatu",
    flag: "🇻🇺",
    code: "VU",
    dial_code: "+678",
    currency: {
      name: "Vatu",
      description: "Vanuatu Vatu",
      code: "VUV",
      symbol: "VT",
    },
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "🇻🇪",
    code: "VE",
    dial_code: "+58",
    currency: {
      name: "Bolívar",
      description: "Venezuelan Bolívar",
      code: "VES",
      symbol: "Bs",
    },
  },
  {
    name: "Vietnam",
    flag: "🇻🇳",
    code: "VN",
    dial_code: "+84",
    currency: {
      name: "Dong",
      description: "Vietnamese Dong",
      code: "VND",
      symbol: "₫",
    },
  },
  {
    name: "Virgin Islands, British",
    flag: "🇻🇬",
    code: "VG",
    dial_code: "+1284",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Virgin Islands, U.S.",
    flag: "🇻🇮",
    code: "VI",
    dial_code: "+1340",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
  {
    name: "Wallis and Futuna",
    flag: "🇼🇫",
    code: "WF",
    dial_code: "+681",
    currency: {
      name: "Franc",
      description: "CFP Franc",
      code: "XPF",
      symbol: "₣",
    },
  },
  {
    name: "Yemen",
    flag: "🇾🇪",
    code: "YE",
    dial_code: "+967",
    currency: {
      name: "Rial",
      description: "Yemeni Rial",
      code: "YER",
      symbol: "﷼",
    },
  },
  {
    name: "Zambia",
    flag: "🇿🇲",
    code: "ZM",
    dial_code: "+260",
    currency: {
      name: "Kwacha",
      description: "Zambian Kwacha",
      code: "ZMW",
      symbol: "ZK",
    },
  },
  {
    name: "Zimbabwe",
    flag: "🇿🇼",
    code: "ZW",
    dial_code: "+263",
    currency: {
      name: "Dollar",
      description: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
  },
];
